spring:
  boot:
    admin:
      context-path: /admin
      client:
        url: http://localhost:8080/admin
        instance:
          prefer-ip: true
  data:
    rest:
      base-path: /api/rest

management:
  endpoints:
    web:
      exposure:
        # Exposing all endpoints in dev. In prod, expose only what is needed.
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: when-authorized
  info:
    env:
      enabled: true
